const data = {
  "steep": "крутой",
  "bumpy": "неровный",
  "scatter plot": "график рассеяния",
  "raw": "сырье",
  "raw data": "необработанные данные",
  "define": "определять",
  "predict": "прогнозировать",
  "obviously": "очевидно",
  "misclassifying": "неправильной классификации",
  "equivalent": "эквивалент",
  "common": "общий",
  "ahead": "впереди",
  "supervised": "контролируемый",
  "convention": "соглашение",
  "derivation": "вывод",
  "improvement": "улучшение",
  "essence": "сущность",
  "entry": "запись",
  "evaluate": "оценивать",
  "quantify": "количественного",
  "whether": "будь то",
  "accuracy": "точность",
  "might": "мог бы",
  "computers": "компьютеры",
  "depth": "глубина",
  "tedious": "утомительный",
  "dissect": "рассекать",
  "препарировать": "dissect",
  "stick": "придерживаться",
  "probabilistic inference": "вероятностное умозаключение",
  "tough one": "крепкий орешек",
  "tough": "жесткий",
  "occurs": "имеет место",
  "sensitivity": "чувствительность",
  "reduce": "уменьшить",
  "a tear": "слеза",
  "behavior": "поведение",
  "advocate": "адвокат",
  "harsh": "суровый",
  "caught up": "догнали",
  "meditating": "медитации",
  "amount": "количество",
  "exception": "исключение",
  "habit": "привычка",
  "swallowing": "проглатывание",
  "cruel": "жестокий",
  "dread": "страшиться",
  "involved": "участвует",
  "raise": "повышать",
  "steer": "управлять",
  "dumped": "сбрасывали",
  "dump": "свалка",
  "terrific": "потрясающий",
  "me neither": "и я нет",
  "tan": "загар",
  "blame": "вина",
  "blaming": "обвинять",
  "circumstances": "обстоятельства",
  "commit": "совершить",
  "commit in memory": "фиксации в памяти",
  "therefore": "следовательно",
  "cause": "причина",
  "определенно": "definitely",
  "angle": "угол",
  "rely on": "полагаться на",
  "blameless": "безупречный",
  "orphan": "сирота",
  "wit": "остроумие",
  "nag": "пилить",
  "rambles on": "на бродит",
  "upset": "рассториться",
  "mattress": "матрас",
  "stuffing": "начинка",
  "tidy": "аккуратный",
  "crux": "суть",
  "sip": "глоток",
  "parole officer": "\"должностное лицо",
  "concern": "беспокойство",
  "pins": "штифты",
  "keenness": "увлеченность",
  "inkwells": "чернильницы",
  "mourn": "оплакивать",
  "slick": "скользкий",
  "counts": "счетчики",
  "count": "подсчитывать",
  "should": "должен",
  "dishwashing liquid": "посудомоечная жидкость",
  "asleep": "спящий",
  "otherwise": "в противном случае",
  "reset": "сброс",
  "deed": "дело",
  "bloke": "парень",
  "least": "наименее",
  "hip": "тазобедренный",
  "alter": "изменять",
  "constraint": "ограничение",
  "sparse": "редкий",
  "we refer": "мы ссылаемся",
  "invoke": "взывать",
  "verb": "глагол",
  "attempt": "попытка",
  "persist": "сохраняться",
  "occasionally": "время от времени",
  "distinguish": "выделить",
  "treat": "рассматривать",
  "throughout": "на протяжении",
  "altered": "изменен",
  "compromise": "компромисс",
  "best of breed": "лучший представитель породы",
  "elusive": "неуловимый",
  "familiarize ourselves": "познакомимся",
  "unless": "если",
  "guess": "угадай",
  "purposes": "цели",
  "assured": "уверенный",
  "regardless": "несмотря на",
  "match": "совпадение",
  "scatter": "разброс",
  "slope": "склон",
  "co-occur": "сосуществуют",
  "fit": "поместиться",
  "vastly": "значительно",
  "prior": "предшествующий",
  "probability": "вероятность",
  "evidence": "доказательства",
  "posterior": "задний",
  "incorporates": "включает в себя",
  "oddities.": "странности.",
  "fore": "носовой",
  "\"forename": "\"",
  "\"query": "\"",
  "introduces": "вводит",
  "clause": "пункт",
  "restrictions:": "ограничения:",
  "emphasis": "акцент",
  "ponytails": "хвостики",
  "crowd": "толпа",
  "pivot": "стержень",
  "comprehension": "понимание",
  "indices": "индексы",
  "inner": "внутренний",
  "broadcasting": "вещания",
  "strive": "прилагать усилия",
  "capable": "способный",
  "perceives": "воспринимает",
  "precision": "точность",
  "\"\"\"dot product\"\"\"": "\"\"\"скалярное произведение\"\"\"",
  "identity": "тождественность",
  "astonishingly": "изумительно",
  "fraction": "доля",
  "comprises": "включает",
  "roughly": "грубо",
  "concurrently": "одновременно",
  "taught": "учил",
  "encompass": "охватывать",
  "particular": "конкретный",
  "revolve": "вращаться",
  "volve": "вернуться",
  "agenda": "повестка дня",
  "float": "поплавок",
  "fossil": "ископаемое",
  "convincing": "убедительный",
  "onset": "начало",
  "mean time": "среднее время",
  "arrive": "прибыть",
  "bars": "брусья",
  "seminal": "плодотворный",
  "beyond": "за",
  "compose": "составить",
  "frankly": "откровенно",
  "gain momentum": "набирать обороты",
  "contribution": "вклад",
  "admire": "восхищаться",
  "rapid": "быстрый",
  "due": "в связи",
  "inspired": "вдохновенный",
  "holistic": "целостный",
  "similarly": "по аналогии",
  "measure": "измерение",
  "steadily": "постоянно",
  "tend": "иметь тенденцию",
  "to fit": "подходить",
  "overfitting": "переобучения",
  "tremendes": "ужасный",
  "tremende": "огромный",
  "remarkable": "замечательный",
  "to tackle": "заниматься",
  "unsung": "невоспетый",
  "aware": "знать",
  "assignment": "назначение",
  "semantic gap": "семантический разрыв",
  "to be robust": "быть прочным",
  "assume": "предполагать",
  "intraclass variation": "внутренняя изменчивость",
  "obvios": "очевидный",
  "compute a convex hull;": "вычислить выпуклую оболочку;",
  "super brittle": "супер хрупкий",
  "insight": "в поле зрения",
  "dumb": "тупой",
  "to measure": "измерять",
  "backwards": "назад",
  "carving up": "вырезание",
  "fair": "справедливая",
  "unfair": "недобросовестный",
  "independently": "независимо",
  "identically distributed": "одинаково распределенный",
  "alleviate": "смягчать",
  "to spare": "жалеть",
  "snap": "щелчок",
  "divide": "делить",
  "unclear": "не понятно",
  "to quantify": "количественно",
  "определять количество": "quantify",
  "unwieldy": "громоздкий",
  "denote": "обозначать",
  "notion": "понятие",
  "safety margin": "коэффициент безопасности",
  "margin": "поле",
  "hinge": "петля",
  "faintly": "слабо",
  "jiggle": "покачивать",
  "trade off": "компромисс",
  "canonical": "канонический",
  "encourages": "призывает",
  "somehow": "как-то",
  "penalty": "штраф",
  "sparsity": "разреженность",
  "convolutional": "сверточного",
  "endow": "наделять",
  "mass": "масса",
  "error prone": "склонный к ошибкам",
  "exact": "точный",
  "derive": "получить",
  "span": "службы",
  "comprehensions": "постижения",
  "shave": "брить",
  "диапазон": "range of",
  "rude": "грубый",
  "convolution": "свертки",
  "я предполагаю": "i suppose",
  "comprehensive": "комплексный",
  "enterprise": "предприятие",
  "snazzy": "броский",
  "fancy": "маскарадный",
  "figure out": "выяснить",
  "apparent": "очевидный",
  "overall": "в общем и целом",
  "sweet spot": "сладкое пятно",
  "at will": "по желанию",
  "грустная панда": "sad panda",
  "позвоночник": "spine",
  "gossip": "слухи",
  "refuse to be  content": "отказываться от содержания",
  "auxiliary": "вспомогательный",
  "hardly ever": "почти никогда",
  "scariest": "страшный",
  "tuple": "кортеж",
  "engaged": "занято",
  "disaster": "катастрофа",
  "bite": "укусить",
  "evolve": "эволюционировать",
  "feedback": "обратная связь",
  "certain": "определенный",
  "indicated": "указанный",
  "indicate": "указывать",
  "overlap": "перекрытие",
  "advantages": "преимущества",
  "crucial": "ключевой",
  "granularity": "зернистость",
  "unduly": "чрезмерно",
  "disease": "болезнь",
  "clue": "ключ к разгадке",
  "abuse": "злоупотребление",
  "pipeline": "трубопровод",
  "assumptions": "допущения",
  "apparently": "по всей видимости",
  "lamb": "ягненок",
  "whimsical": "капризный",
  "capable-yet-misunderstood": "\"способный",
  "forever": "навсегда",
  "to not bloat the amount of stuff": "не раздувать количество вещей",
  "encounter": "столкновение",
  "wreak havoc": "наносить ущерб",
  "to be aware": "быть в курсе",
  "considered": "считается",
  "stencil": "трафарет",
  "experiencing some “jank” during the paint step": "испытывая некоторый «удар» во время этапа paint",
  "bounce": "подпрыгивать",
  "elaborate": "разрабатывать",
  "awkward": "неловко",
  "at least": "как минимум",
  "were at least": "были по крайней мере",
  "dazzle": "ослепление",
  "to corral": "загон",
  "capabilities": "возможности",
  "anticipating": "предвидение",
  "flaw": "изъян",
  "intellectual wildcard": "интеллектуальный подстановочный знак",
  "nail on chalkboard": "гвоздь на доске",
  "regret": "сожаление",
  "issue": "вопрос",
  "impedance": "импеданс",
  "sequel": "продолжение",
  "последствие": "consequence",
  "distract": "отвлекать",
  "подменить": "substitute",
  "tension": "напряженность",
  "сравнение": "comparison",
  "scarce": "дефицитный",
  "tiny": "крошечный",
  "effort": "усилие",
  "pile-up": "нагромождение",
  "nail": "гвоздь",
  "groceries": "бакалейные товары",
  "straightforward": "простой",
  "twisted": "скрученный",
  "drawbacks": "недостатки",
  "pitfalls": "подводные камни",
  "dinky": "нарядный",
  "acquire": "приобретать",
  "precisely": "точно",
  "precise": "точный",
  "ambiguous": "двусмысленный",
  "nuance": "нюанс",
  "profound": "глубокий",
  "appear": "появиться",
  "vice-versa": "наоборот",
  "subtle": "тонкий",
  "insanity": "невменяемость",
  "would be insanity": "было бы безумием",
  "back and forth": "назад и вперед",
  "grasp": "схватывание",
  "recap": "резюмировать",
  "smoothing": "сглаживающий",
  "shear": "сдвиг",
  "hebrew": "иврит",
  "even": "даже",
  "dimwitted": "неумный",
  "variance": "дисперсия",
  "obtain": "получать",
  "spread": "распространение",
  "dense": "плотный",
  "skip-gram": "пропустить грамм",
  "appearing": "появляясь",
  "obvious": "очевидный",
  "average": "в среднем",
  "response": "ответ",
  "narrow": "узкий",
  "narrowing": "уменьшение",
  "adjacent": "примыкающий",
  "roll up": "свернуть",
  "streamlined": "обтекаемый",
  "governance": "управление",
  "coward": "трус",
  "depraved": "развращенный",
  "attitude": "отношение",
  "behind": "позади",
  "wretched": "несчастный",
  "though": "хоть",
  "wretch": "негодяй",
  "dare": "сметь",
  "generosity": "щедрость",
  "attic": "чердак",
  "hauling": "перевозка",
  "embarrassing": "затруднительный",
  "slightly": "немного",
  "to work through": "проработать",
  "through": "через",
  "thoughts": "мысли",
  "comprehensible input": "понятный ввод",
  "lacks": "не хватает",
  "lean on": "опираться на",
  "to persist": "настаивать",
  "regrets": "сожаления",
  "confidence": "уверенность",
  "delusion": "наваждение",
  "ordinary": "обычный",
  "owe": "задолжать",
  "envy": "зависть",
  "roam": "странствовать",
  "совесть": "conscience",
  "rebuffed": "отвергнута",
  "occupational hazard": "профессиональный риск",
  "dozen": "дюжина",
  "look up": "уважать",
  "to embark": "вступать",
  "i was conceived in": "я был зачат в",
  "fair skin": "светлая кожа",
  "burdensome": "обременительный",
  "burdens": "бремя",
  "veins": "вены",
  "dismay": "испуг",
  "rufus": "руфус",
  "to disclose": "раскрывать",
  "convinient": "удобный",
  "pail": "ведерко",
  "burying": "похоронив",
  "pageant": "маскарад",
  "оскорбительный": "offensive",
  "move forward": "двигаться вперед",
  "douchebag": "придурок",
  "tenet": "догмат",
  "engage": "заниматься",
  "converge": "сходиться",
  "mention": "упомянуть",
  "consequences": "последствия"
};